In [1]:
import pickle

In [2]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [3]:
X

array([[[106,  81, 101, ..., 114, 121,  84],
        [ 97, 127,  81, ..., 108,  86, 120],
        [163,  88,  96, ...,  75, 130,  66],
        ...,
        [170, 154, 197, ..., 152, 138, 122],
        [178, 183, 166, ..., 171, 125, 139],
        [186, 188, 178, ..., 195, 173, 148]],

       [[134, 130, 129, ..., 207, 205, 205],
        [134, 129, 133, ..., 214, 213, 212],
        [135, 133, 131, ..., 227, 226, 223],
        ...,
        [136, 139, 124, ..., 180, 121, 108],
        [172, 126, 102, ..., 165, 103,  87],
        [228, 231, 234, ..., 203, 149, 107]],

       [[224, 254, 255, ..., 154, 151, 195],
        [203, 250, 255, ..., 161, 164, 195],
        [159, 224, 255, ..., 170, 146, 194],
        ...,
        [253, 254, 254, ..., 255, 255, 255],
        [253, 254, 254, ..., 255, 255, 255],
        [255, 253, 255, ..., 255, 255, 255]],

       ...,

       [[101,  97, 106, ..., 254, 254, 254],
        [ 92, 123, 107, ..., 224, 252, 252],
        [ 93, 102, 102, ..., 215, 199, 125

In [4]:
y

array([1, 0, 1, ..., 1, 0, 0])

In [5]:
X = X/255

In [6]:
X

array([[[0.41568627, 0.31764706, 0.39607843, ..., 0.44705882,
         0.4745098 , 0.32941176],
        [0.38039216, 0.49803922, 0.31764706, ..., 0.42352941,
         0.3372549 , 0.47058824],
        [0.63921569, 0.34509804, 0.37647059, ..., 0.29411765,
         0.50980392, 0.25882353],
        ...,
        [0.66666667, 0.60392157, 0.77254902, ..., 0.59607843,
         0.54117647, 0.47843137],
        [0.69803922, 0.71764706, 0.65098039, ..., 0.67058824,
         0.49019608, 0.54509804],
        [0.72941176, 0.7372549 , 0.69803922, ..., 0.76470588,
         0.67843137, 0.58039216]],

       [[0.5254902 , 0.50980392, 0.50588235, ..., 0.81176471,
         0.80392157, 0.80392157],
        [0.5254902 , 0.50588235, 0.52156863, ..., 0.83921569,
         0.83529412, 0.83137255],
        [0.52941176, 0.52156863, 0.51372549, ..., 0.89019608,
         0.88627451, 0.8745098 ],
        ...,
        [0.53333333, 0.54509804, 0.48627451, ..., 0.70588235,
         0.4745098 , 0.42352941],
        [0.6

In [7]:
X = X.reshape(-1, 60, 60, 1)

In [8]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [9]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [10]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [11]:
model.fit(X, y, epochs=5, validation_split=0.1)

Epoch 1/5


141/141 [==============================] - 14s 84ms/step - loss: 0.6915 - accuracy: 0.5458 - val_loss: 0.6732 - val_accuracy: 0.5900
Epoch 2/5
141/141 [==============================] - 11s 79ms/step - loss: 0.6446 - accuracy: 0.6376 - val_loss: 0.6499 - val_accuracy: 0.6540
Epoch 3/5
141/141 [==============================] - 11s 79ms/step - loss: 0.5924 - accuracy: 0.6853 - val_loss: 0.6295 - val_accuracy: 0.6640
Epoch 4/5
141/141 [==============================] - 11s 78ms/step - loss: 0.5405 - accuracy: 0.7296 - val_loss: 0.6269 - val_accuracy: 0.6440
Epoch 5/5
141/141 [==============================] - 15s 108ms/step - loss: 0.4737 - accuracy: 0.7691 - val_loss: 0.5985 - val_accuracy: 0.6940


In [12]:
X.shape

(5000, 60, 60, 1)

In [13]:
import time

time.time()

1707476988.6617117

In [14]:
type(1707310532.2506883)

float